#!/bin/sh

# This script performs similar security routines that can be found
# in the mysql_secure_installation script that comes with MariaDB.

MYSQL="/usr/bin/mysql"

# Start MariaDB
#--------------

/sbin/service mariadb start 2>/dev/null

# Remove anonymous users
#-----------------------

CHECK=`$MYSQL -uroot -e "SELECT * FROM mysql.user WHERE User='';" mysql 2>/dev/null`

if [ -n "$CHECK" ]; then
    logger -p local6.notice -t installer "app-mariadb-core - removing anonymous users"
    $MYSQL -uroot -e "DELETE FROM mysql.user WHERE User='';" mysql
fi

# Remove remote root login
#--------------------------

CHECK=`$MYSQL -uroot -e "SELECT * FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1');" mysql 2>/dev/null`

if [ -n "$CHECK" ]; then
    logger -p local6.notice -t installer "app-mariadb-core - removing remote root login"
    $MYSQL -uroot -e "DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1');" mysql
fi


# Remove test database
#---------------------

CHECK=`$MYSQL -uroot -e "SHOW TABLES" test 2>/dev/null` 

if [ $? -eq 0 ]; then
    logger -p local6.notice -t installer "app-mariadb-core - removing test database"
    $MYSQL -uroot -e "DROP DATABASE test;" mysql
    $MYSQL -uroot -e "DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%'" mysql
fi

# Stop MariaDB
#-------------

/sbin/service mariadb stop 2>/dev/null
